services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mots'
      - 'MYSQL_PASSWORD=B@sketballa01'
      - 'MYSQL_USER=root'
      - 'MYSQL_ROOT_PASSWORD=B@sketballa01'

    ports:
      - '3306'
  application:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/mots?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: B@sketballa01
volumes:
  mysql-data: